config/routes.rb
Craigslist::Application.routes.draw do

  resources :users
  resources :posts
  resources :categories

  get '/logout' => 'users#logout'

  post '/users/login' => 'users#login'

  root 'users#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  has_many :posts

  include BCrypt

  def password=(secret)
    return if secret == ''
    @password = Password.create(secret)
    self.password_digest = @password
  end

  def password
    return unless password_digest
    @password ||= Password.new(self.password_digest)
  end


  def self.authenticate(params)
    user = User.find_by_email(params[:email])
    return user if user && (user.password == params[:password])
    nil  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    if post
      User.find(session[:user_id]).posts << post
      redirect_to user_path(session[:user_id])
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @category = Category.find(@post.category_id)
    render 'show'
  end

  private

    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
  end

  def new
    @user = User.new
  end

  def login
    user = User.authenticate(login_params)
    if user
      reset_session
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      render 'index'
    end
  end

  def create
    user = User.new(create_params)
    if user.save
      reset_session
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      render 'new'
    end
  end

  def show
  end

  def logout
    reset_session
    redirect_to root_path
  end

  private

    def create_params
      params.require(:user).permit(:username, :email, :password)
    end

    def login_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigslist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<h1>Create a new post bro</h1>

<%= form_for @post, url: {action: 'create' } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :body %>
  <%= f.text_area :body %><br>
  <h4>Choose category</h4>
  <% Category.all.each do |cat| %>
    <%= f.label :category, cat.name %>
    <%= f.radio_button :category, cat %><br>
  <% end %>
  <%= f.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<h1>Welcome <%= current_user.username %></h1>

<h3>Title: <%= @post.title %></h3>

<p>Body: <%= @post.body %></p>
<p>Category: <%= @category.name %></p>


<h5><%= link_to("Back Home", user_path) %></h5>

app/views/users/index.html.erb
<h1>Bro... Yolo</h1>
<%= form_for @user, url: {action: 'login'} do |f|%>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Log in bro"%>
<% end %>

<h5><%= link_to("Create account bro", new_user_path ) %></h5>

app/views/users/new.html.erb
<h1>Create a new Account Bro</h1>
<%= form_for @user do |f|%>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create bro"%>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.username %></h1>

<h3>Your current posts</h3>
<ul>
  <% current_user.posts.each do |post| %>
    <li><%= link_to( post.title , post_path(post)) %></li>
  <% end %>
</ul>

<h4><%= link_to("Create a new post", new_post_path(current_user.id)) %></h4>


<h5><%= link_to("Logout", logout_path) %></h5>